global:
  evaluation_interval: 10s
  scrape_interval: 10s

scrape_configs:
  - job_name: 'ssp-metrics'
    metrics_path: /api/v1/actuator/prometheus
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8080']